language: cpp

compiler:
- gcc
- clang
os:
 - linux

jobs:
  include:
  - name: "all projects"
    script:
    - cmake -H. -B_build
    - cmake --build _build
  - name: "each CMakeLists.txt"

script:
- source ./script
- cd /home/travis/build/TheRealMal/lab06/solver_application/_build
- cpack -G DEB
    

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

deploy:
  provider: releases
  api_key:
    secure: "kXNPXxqCpxjRqMDNsn/b4WUJ4pDNDwBqMwvZIxvN6mN5+qzqjpMWwT2GI7sufgFIN/DGVZQi3n/WcA3xvlo61XWhTxkgaEaTdYH0vIFSxGIBy5m+U0K14mW7coqO86cD6pX3B0UzJvdJn+fE1Mt4zRR+Fbbl4g5+fGd+nNyOnb0gT8OjRUVVplG6aC5YCbUeF0mXxoBW0sM0XcUdCc69Lq2gZkIY+1Afb2mLlYokCapJiKTl5CrHGaI+wvlX8flhRVJntL9D/73z1oWBFhPBa0mqaKd/dDPHjtXZBtDcs/0Z/9cL3insKGqkzQNGjWdgStddtF2h8DIG3DCMCGgSnUS2a7IcGjxCZVGlpQi2KxIhTzY0/cSSyWZJJOD/AllK5WCN8IqOhLS2eg1AKCwlyNT/iPLAppIUY6OrkWbnVLDuLmvucGICworE21pDQ9VQOxXr9fb36bT+cr0OIbgWq2dgo1cQFNfWOWrkmJw2yCHCh68OWHIQsc0uT7XyqK9433500ful1R+c92oK2UndNSIanxUCFUPka3tOXCU8dP+21VqXb44M7qGJc10FaE94P66ShEZ4GQMo/9erMPAUCkT+QLcDIwSPOaoJG9hPD21Ggc+4kjyRXHaT1NErrSlBhHaF3uR+JuhU7BruHWQbL5Q9Hx/whekUfncSd0TXhpI="
  file: "/home/travis/build/TheRealMal/lab06/solver_application/_build/solver-0.1.0.0-Linux.deb"
  skip_cleanup: true
  on:
    branch: main
